controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

# PUNTO
app_acumulador_punto:
    path: /api/acumulador-punto
    controller: App\Punto\Infrastructure\Api\AcumuladorPuntoController::acumuladorDePuntos
    methods: [POST]

app_canjeador_punto:
    path: /api/canjeador-punto
    controller: App\Punto\Infrastructure\Api\CanjeadorPuntoController::canjeadorDePuntos
    methods: [POST]

app_punto_no_canjeado_por_cliente:
    path: /api/cliente-puntos-disponibles
    controller: App\Punto\Infrastructure\Api\PuntoDelClienteSinCanjearController::puntosNoCanjeadosDelCliente
    methods: [GET]

# FARMACIA
app_contador_punto_no_canjeado:
    path: /api/puntos-sin-canjear
    controller: App\Farmacia\Infrastructure\Api\ContadorPuntoNoCanjeadoController::contadorDePuntosNoCanjeadosEnFarmacia
    methods: [GET]

app_contador_punto_no_canjeado_por_cliente:
    path: /api/client-puntos-sin-canjear
    controller: App\Farmacia\Infrastructure\Api\ContadorPuntoNoCanjeadoController::contadorDePuntosNoCanjeadosEnFarmaciaPorCliente
    methods: [GET]