controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# PUNTO
app_acumulador_punto:
    path: /acumulador-punto
    controller: App\Punto\Infrastructure\Api\AcumuladorPuntoController::acumuladorDePuntos
    methods: [POST]

app_canjeador_punto:
    path: /canjeador-punto
    controller: App\Punto\Infrastructure\Api\CanjeadorPuntoController::canjeadorDePuntos
    methods: [POST]

# FARMACIA
app_contador_punto_no_canjeado:
    path: /puntos-sin-canjear
    controller: App\Farmacia\Infrastructure\Api\ContadorPuntoNoCanjeadoController::contadorDePuntosNoCanjeadosEnFarmacia
    methods: [GET]

app_contador_punto_no_canjeado_por_cliente:
    path: /client-puntos-sin-canjear
    controller: App\Farmacia\Infrastructure\Api\ContadorPuntoNoCanjeadoController::contadorDePuntosNoCanjeadosEnFarmaciaPorCliente
    methods: [GET]