controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_acumulador_punto:
    path: /acumulador-punto
    controller: App\Punto\Infrastructure\Api\AcumuladorPuntoController::acumuladorDePuntos
    methods: [POST]

app_canjeador_punto:
    path: /canjeador-punto
    controller: App\Punto\Infrastructure\Api\CanjeadorPuntoController::canjeadorDePuntos
    methods: [POST]